added e2e test for oauth flow including signing of contract
nuts-foundation/nuts-go-e2e-test pull request #1
Opened 2020-12-01 10:43 UTC by woutslakhorst

It requires some changes on nuts-crypto, nuts-go-core and nuts-auth first.

2020-12-07 14:46 UTC, reinkrul requested changes
When I try to run using a build from latest master it fails;

```
------------------------------------
Obtain client certificate...
------------------------------------
read EC key
writing EC key
FAILED: Could not get TLS client certificate from node-B
{"message":"Not Found"}
```

What I also see:
```
nodeB_1          | time="2020-12-07T14:43:31Z" level=error msg="Status code: 0" err="*irma.SessionError"
...
nodeB_1          | {"time":"2020-12-07T14:43:34.657283Z","id":"","remote_ip":"172.22.0.1","host":"localhost:21323","method":"POST","uri":"/crypto/certificate/tls","user_agent":"curl/7.64.1","status":404,"error":"code=404, message=Not Found","latency":49200,"latency_human":"49.2µs","bytes_in":178,"bytes_out":24}
```

2020-12-07 14:46 UTC, reinkrul commented on oauth-flow/run-test.sh
> +sed "s/BASE64_CONTRACT/$(cat ./node-B/data/contract.txt)/" ./node-B/createsigningsessionrequesttemplate.json > ./node-B/data/createsigningsessionrequest.json
That's some proper Bash-fu you've got going there!

2020-12-07 14:56 UTC, woutslakhorst commented
> When I try to run using a build from latest master it fails;

yes waiting for some other PR's

2020-12-09 12:26 UTC, woutslakhorst commented
@reinkrul latest master works now

2020-12-10 07:36 UTC, reinkrul commented
> @reinkrul latest master works now

Maste branch of `nuts-go`? I don't see changes there since I last tested, after running it again its still broken?

2020-12-10 08:00 UTC, reinkrul approved these changes
Works, but only on the second time. The first time always leads to a time out while waiting for the services to start.

2020-12-10 12:13 UTC, merged